balena-os/balena-raspberrypi

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi-4.1/fix-egl-apps-while-running-in-containers.patch
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.1.bbappend

This patch is nit applied by default. If needed, activate it by setting:
RPI_FIX_VCHIQ = "1" in your local.conf.
@petrosagg @floion @telphan @lorenzo-stoakes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-raspberrypi/13)

linux-raspberrypi-4.1: Add optional workaround patch for egl apps in containers

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend

Connects to resin-os/meta-resin#133-supervisor-custom-image-tag
@telphan @floion

Custom docker images in connectable builds on resin-raspberrypi

---

CHANGELOG.md

Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

Update meta-resin to include supervisor v2.5.0

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/bblayers.conf.sample

Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek

Add meta-filesystem as we need aufs-utils on resin-raspberrypi

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

This causes problems if people try to modprobe from within their
containers based on either Debian or Ubuntu.

linux-raspberrypi: disable kernel module compression

---

raspberrypi2.coffee

Currently the dashboard defaults to a Raspberry Pi 2 device when creating a new application. Should default to RPi3. This setting is already applied in `raspberrypi3.coffee` (that is currently more than one default is set), so this change just removes the value that overrides the desired default.
Connects to https://github.com/resin-io/hq/issues/439

do not default to RPi2 in the UI (RPi3 instead)

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-support/resin-init/files/resin-init-board
layers/meta-resin-raspberrypi/recipes-support/resin-init/resin-init-board.bbappend

connect https://github.com/resin-os/resinos/issues/201

resin-init-board: modprobe i2c-dev on startup

---

.gitmodules
CHANGELOG.md
tests/boardtest.sh

This PR adds the AutoHAT repo for automated testing on resin-raspberrypi PRs. I have currently set this up for Raspberrypi3 with Jenkins. After this PR the control on whether or not to test lies with Jenkins where testing can be enabled/disabled. Below you can see a sample run with 2 checks - One AutoHAT and then Jenkins. We can make the AutoHAT tests as required in this repo after ensuring that the infrastructure is solid.
The variables used in the script are populated from the Jenkins Job and from Jenkins AutoHAT test rig slaves ( https://github.com/resin-io/autohat-resin-jenkins/blob/master/services/run_slave.sh )
The script is meant to be run from a Jenkins Job which populates the variables needed - https://jenkins.dev.resin.io/view/Yocto/job/AutoHAT-board-Tests/
Closes: …

tests: Enable AutoHAT tests through Jenkins

---

CHANGELOG.md

Update the build scripts on master to 1.X in order to fix meta-resin jenkins builds.

Update build scripts to master on 1.X

---

layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

The .conf file for raspberrypi3-64 from meta-raspberrypi inherits
raspberrypi3 and raspberrypi recipes, leading to a "patch already
applied" error. This is a workaround, the issue was reported upstream.

bluez5: don't apply patches twice for raspberrypi3-64

---

CHANGELOG.md
raspberrypi.coffee
raspberrypi3-64.coffee
raspberrypi3.coffee

raspberrypi.coffee: add imageDownloadAlerts
raspberrypi3-64.coffee: add imageDownloadAlerts
raspberrypi3.coffee: add imageDownloadAlerts
Adds a warning on the download image modal of the dashboard  about the need of an external WiFi adapter in case the user intents to use the RPi on 5GHz WiFi networks.
See: https://github.com/resin-io/resin-ui/issues/1102
See: [arch call 2017-07-19](https://github.com/resin-io/hq/wiki/Architecture-Calls#19-jul-2017)
Signed-off-by: Thodoris Greasidis <thodoris@resin.io>

Add WiFi 5GHz connectivity warning for RPi 3 & Zero W

---

CHANGELOG.md

This includes a fix for building with specific supervisor tags.
Changelog-entry: Update resin-yocto-scripts to master
Signed-off-by: Will Newton <willn@resin.io>

resin-yocto-scripts: Update to latest master

---

CHANGELOG.md

Hopefully this should fix the Jenkins build with Pyro by pulling the latest yocto-build-env.

Update build scripts to latest master

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-core/enable-overcommit/enable-overcommit.bb
layers/meta-resin-raspberrypi/recipes-core/enable-overcommit/files/enable-overcommit.conf
layers/meta-resin-raspberrypi/recipes-core/images/resin-image.bbappend

Golang allocate large region of virtual memory
in order to properly handle several go binaries
process this enables the always overcommit policy.
https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory
Signed-off-by: Yossi Eliaz <yossi@resin.io>

rpi: set always overcommit policy on

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

linux-raspberrypi_%.bbappend: Fix pca955 GPIO expander kernel configs

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend

The flag name has been changed from debug-image to development-image

rpi-config_git.bbappend: Fix obsolete reference to debug-image

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-bsp/bootfiles/bcm2835-bootfiles.bbappend

We do not add to resinOS the files fixup_db.dat and start_db.elf
which are esentially versions of fixup_x.dat and start_x.elf with debug assertions
enabled.
By removing them we free up about 4.8 MB from resin-boot (having less
free space in resin-boot makes it probable that hostapps update will fail when one of the
files in this boot partition grows in size in the future, such as the kernel for example; when
one file in resin-boot is bigger than the available free space, hostapps update will error out
because it tries to do an atomic update of the bootfiles).

bcm2835-bootfiles: Exclude from resinOS the firmware files with debug asssertions

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend
layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/files/brcm43438.service

We unmask the brcm43438.service systemd service so that bluetooth is enabled
by default from the host OS.
If users load a dtb overlay to switch from uart0 to uart1, this would make
the brcm43438.service not work anymore since this service is hardcoded to
use ttyAMA0 and specific baudrate. In such cases, it is the user's responsability
to run hciattach with the correct parameters through the user container, based on
the uart he has switched to.

bluez5_%.bbappend: Unmask brcm43438.service

---

CHANGELOG.md
fincm3.coffee

There already is the following instruction:
"Your device should appear in your application dashboard within a few minutes. Have fun!"

fincm3.coffee: Remove superfluous wait instruction

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

Changing to sumo branch, the brcm43438.service systemd service wasn't getting installed in the
raspberry pi zero wireless rootfs.

bluez5_%.bbappend: Fix bluetooth on rpi zero wireless

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-connectivity/networkmanager/networkmanager_%.bbappend

We do this to workaround a bug where the WiFi firmware won't reconnect after entering power save mode
(the proper fix would be to use a wifi firmware which does not have this bug but at this point we do
not have such firmware).

networkmanager: Disable WiFi powersave mode for Balena Fin

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot/rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

U-boot by default embeds a dtb inside the binary.
In resinOS, we'd like u-boot to use the firmware loaded by the pi firmware.
This PR does that
Fixes https://github.com/resin-os/resin-raspberrypi/issues/228

Use the dtb overlays loaded by Pi firmware instead of u-boot built-in

---

layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

linux-yocto: Enable I2C and GPIO support for Kontron PLD devices

---

layers/meta-resin-raspberrypi/recipes-bsp/u-blox-modeswitch/u-blox-modeswitch.bb
layers/meta-resin-raspberrypi/recipes-core/udev/udev-rules-rpi.bbappend

The /etc/udev/rules.d directory will be used by custom udev rules when https://github.com/resin-os/meta-resin/pull/1206 is merged.
Install the rules in /lib/udev/rules.d instead of /etc

Move udev rules from /etc to /lib

---

layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

The current integration in uboot uses the ext bootcount driver which
doesn't use upgrade_available. The entire rollback support design is
currently based on this variable (upgrade_available) so if that is not
taken into consideration the board will increment bootcount with every
boot breaking the board after the first boot. Disable for now this
feature.
Changelog-entry: Disable rollbacks
Signed-off-by: Andrei Gherzan <andrei@balena.io>

u-boot: Disable rollbacks

---

layers/meta-resin-raspberrypi/recipes-kernel/sd8887-mrvl/sd8887-mrvl.bb

This was moved when renamed from resin to balena
Changelog-entry: Use new balena source repo for SRC_URI

sd8887-mrvl/sd8887-mrvl.bb: Use new source repo for SRC_URI

---

layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

We use currently kernel 4.14.68 and in this version bcm2708_wdog
is no longer present, instead bcm2835_wdt is used. So we remove
the obsolete module and make sure the new module is built-in.
Changelog-entry: Clean-up old bcm2708_wdog watchdog module

linux-raspberrypi_%.bbappend: Cleanup rpi watchdog

---

layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot/rpi-Add-autoboot-configuration-in-defconfigs.patch
layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

We disable autoboot stopping by pressing any key combinations because
there are cases where other ICs are connected to the pi's UART and it
is possible that the other ICs are sending the particular autoboot
stop combination over UART.
Changelog-entry: Set autoboot with no delay, with no check for abort

u-boot: Set autoboot with no delay, with no check for abort

---

layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

Enable the PCA963X LED driver module so we also support boards incorporating this family of integrated circuits.
fixes  #280 
Changelog-entry: Enable the PCA963X LED driver module so we also support boards incorporating this family of integrated circuits.
Signed-off-by: Carlo Maria Curinga <carlo@balena.io>

linux-raspberrypi: Enable PCA963X led driver

---

layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot/increase-usb-interface-nr.patch
layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

This fixes the "Too many USB interfaces!" error thrown by u-boot when
having lots of USB devices connected to the bus
Changelog-entry: u-boot: Increase to 16 the USB interfaces number
Signed-off-by: Sebastian Panceac <sebastian@balena.io>

u-boot: Increase to 16 the USB interfaces number

---

layers/meta-resin-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend

This commit removes the "enable_uart=1" from config.txt
in debug builds to prevent u-boot from sending logs on
UART of RevPi Core3.
RevPi Core3 uses the UART interface to communicate with the
modules on RS485
Changelog-entry: rpi-config: Prevent u-boot UART logging on RevPi Core3
Signed-off-by: Sebastian Panceac <sebastian@balena.io>

rpi-config: Prevent u-boot UART logging on RevPi Core3

---

layers/meta-resin-raspberrypi/recipes-kernel/linux/kernel-devsrc.bbappend

On the rpi3 64 bits the build fails with the following error:
| /yocto/resin-board/build/tmp/work/raspberrypi3_64-poky-linux/
kernel-devsrc/1.0-r0/image/usr/src/kernel/scripts/Makefile.clean:15
/yocto/resin-board/build/tmp/work/raspberrypi3_64-poky-linux/
kernel-devsrc/1.0-r0/image/usr/src/kernel/arch/arm64/boot/dts/broadcom/
../overlays/Makefile: No such file or directory
| make[4]: *** No rule to make target '/yocto/resin-board/build/tmp/work
/raspberrypi3_64-poky-linux/kernel-devsrc/1.0-r0/image/usr/src/kernel/
arch/arm64/boot/dts/broadcom/../overlays/Makefile'.  Stop.
| /yocto/resin-board/build/tmp/work/raspberrypi3_64-poky-linux/
kernel-devsrc/1.0-r0/image/usr/src/kernel/scripts/Makefile.clean:89
recipe for target 'arch/arm64/boot/dts/broadcom/../overlays' failed
| make[3]: *** …

kernel-devsrc: Add missing symlink for rpi3 arm64

---

layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot/rpi.h-Remove-usb-start-from-CONFIG_PREBOOT.patch
layers/meta-resin-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

u-boot currently scans usb devices during initialisation. This adds roughly 1-2 seconds of delay during boot. 
We don't need to check for usb devices on the pi as we don't flash an emmc from a usb device.
When https://github.com/balena-os/meta-balena/pull/1432 is merged in meta-balena, the default will be that usb devices won't be scanned for the presence of a flasher image either.

Do not scan for usb devices during boot

---

layers/meta-resin-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bb
layers/meta-resin-raspberrypi/recipes-kernel/picontrol/picontrol.bb

The kernel branch that Kunbus currently ships for their hardware
is revpi-4.9.
Changelog-entry: Switch revolution pi kernel to version 4.9

linux-kunbus.bb: Switch to version 4.9

---

layers/meta-resin-raspberrypi/recipes-support/hostapp-update-hooks/files/9999-bootfiles
layers/meta-resin-raspberrypi/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend

New balenaOS for revpi-core-3 will not boot if the config.txt
has an older dtoverlay=mmc entry.
Therefore we must add a hostapp update hook to remove this entry.
We name this quirk 9999-bootfiles to be sure it is run at the very
end so that no other hooks that may fail would run after it and as
such ending up rebooting in the older OS but with config.txt modified
by this quirk hook.
Changelog-entry: Add config.txt entry removal quirk for revpi-core-3

hostapp-update-hooks: Add config.txt quirk for revpi-core-3

---

layers/meta-resin-raspberrypi/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend

Customers are using wifi chipsets needing mt7601u firmware on rpi0
Changelog-entry: Add mt7601u firmware to rootfs for rpi0

packagegroup-resin-connectivity: Add mt7601u firmware to rootfs for rpi0

---

.gitmodules
layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

The Balena Fin does not use this chipset
Chnagelog-entry: Remove brcm43438 service from the Balena Fin rootfs

bluez5_%.bbappend: Remove brcm43438 service from fincm3 rootfs

---

npe-x500-m3.coffee

Use Yocto Thud for the NPE X500 M3 board

---

layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

The pi-bluetooth gets chained in through
a dependency in bluetooth, in thud. This dependency
is defined in bluez5 and matches the machine.
Currently, the raspberrypi BSP only does it for
raspberrypi zero wireless and raspberrypi3.
To adapt this for the balena machine setup (which has
raspberrypi and raspberrypi zero wireless support in the
same machine) the same dependency needs to be added.
Changelog-entry: Add bluetooth dependency for the raspberrypi machine
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>

bluez5_%.bbapend: Add BT dependency for the Balena machine

---

layers/meta-balena-raspberrypi/recipes-core/images/resin-image.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bb

The linux-kunbus source at version 4.9.76 has no device tree
called bcm2708-rpi-zero-w.dtb so we remove the reference to it
in order to avoid a build error.
Changelog-entry: revpi-core-3: Remove reference to non-existent device tree called bcm2708-rpi-zero-w.dtb in linux-kunbus version 4.9.76

linux-kunbus.bb: Remove non-existing device tree reference

---

layers/meta-balena-raspberrypi/recipes-kernel/sd8887-mrvl/sd8887-mrvl.bb

We update to release 15.68.19.p22 for wlan and
15.26.19.p22 for bt.
Changelog-entry: Update sd8887-mrvl driver to 15.68.19.p22 for wlan and 15.26.19.p22 for bt

sd8887-mrvl: Update wlan and bt releases

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/bcm2835-bootfiles.bbappend

Do not add in balenaOS the files fixup4db.dat and start4db.elf which
are esentially versions of fixup4x.dat and start4x.elf with debug
assertions enabled.
Also remove all the old boot firmware which is present in the boot
partition (this older boot firmware is the one used for RaspberryPi
versions before version 4)
Changelog-entry: Remove debug and old boot firmware for RaspberryPi 4

bcm2835-bootfiles: Remove debug and old boot firmware for rpi4

---

layers/meta-balena-raspberrypi/recipes-core/resin-extra-udev-rules/files/86-nm-unmanaged-fin.rules
layers/meta-balena-raspberrypi/recipes-core/resin-extra-udev-rules/resin-extra-udev-rules.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0005-balena-fin-wifi-sta-uap-mode.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/sd8887-mrvl/sd8887-mrvl.bb

This PR contains three commits:
* Including the latest Fin WiFi driver fix for AP mode
* Exposing the uAP interface through the device tree
* Adding an udev rule for marking it as unmanaged by NM

Exposing uAP interface on balenaFin

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/bcm2835-bootfiles.bbappend

For rpi4 the bootcode is in an SPI EEPROM:
https://www.raspberrypi.org/documentation/hardware/
raspberrypi/booteeprom.md
Changelog-entry: Do not deploy bootcode.bin to boot partition for rpi4 as now the bootcode lives in an EEPROM

bcm2835-bootfiles: Do not deploy bootcode.bin for rpi4

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0002-raspberrypi-Disable-simple-framebuffer-support.patch

The previous patch was faulty and caused a reboot loop when
booting without the vc4-kms-v3d overlay and also having console
defined to something other than null. (for example .dev images
from which one would remove the vc4-kms-v3d overlay defined in
config.txt)
Changelog-entry: Rework the simplefb removal patch from u-boot in order to fix a reboot loop issue on .dev images that did not use the vc4-kms-v3d overlay

u-boot: Rework the simplefb removal patch

---

layers/meta-balena-raspberrypi/conf/samples/local.conf.sample

We leave this overlay enabled only for RaspberryPi 4 so that we are
in sync with already deployed devices. We will enable it here again
eventually when this setting is managed by the supervisor in the
saved target state.
Changelog-entry: Do not enable the vc4-kms-v3d overlay for non-rpi4 devices

meta-balena-raspberrypi:local.conf.sample: Do not enable vc4-kms-v3d

---

layers/meta-balena-raspberrypi/recipes-core/resin-extra-udev-rules/files/86-nm-unmanaged-fin.rules

The maker of the balenaFin WiFi module (Taiyo Yuden) has two MAC address ranges, so we should not filter the uAP interface by MAC address range, but only by name.
Changelog-entry: Do not filter balenaFin uAP interface by address
Signed-off-by: Zahari Petkov <zahari@balena.io>

resin-extra-udev-rules.bbappend: Do not filter balenaFin uAP interface by address

---

layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0006-overlays-Add-Hyperpixel4-overlays.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend
raspberrypi.coffee

This is an overlay used for the Pimoroni Hyperpixel 4.0 display.
Changelog-entry: Add to rootfs the overlay for Pimoroni Hyperpixel 4.0 display

meta-balena-raspberrypi:layer.conf: Add hyperpixel4.dtbo to rootfs

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-Fbcon-ignore-events-for-rpi-sense-fb.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

If fbcon binds to the Sensehat's 8x8 display
framebuffer, various crashes will appear
when preparing images for being drawn
on the display, in the fbdev core.
This small display is not meant for console,
therefore fbcon should not takeover the fb
created by its' driver.
Kernel panics do not occur if another
framebuffer is already present and used,
as console is not switched to this new one.
That's why enabling hdmi_force_output
makes the issue dissapear.

[RPI4] Avoid kernel panic if booting with Sensehat

---

layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend

Kernel update uncovered an issue with modules
being loaded from the new os container during hup.
Loading modules with a new version from the new OS
will trigger failure of the hup hook.
Disable this hook temporarily so we can fix
the issues we uncovered during release testing.

hostapp-update-hooks: Disable eeprom update temporarily

---

layers/meta-balena-raspberrypi/recipes-bsp/rpi-eeprom/rpi-eeprom_git.bb
layers/meta-balena-raspberrypi/recipes-core/images/resin-image.bbappend
layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/files/97-vl805fw
layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend

This PR adds support for vl805 firmware update, as requested in https://github.com/balena-os/balena-raspberrypi/issues/383
<strike>vl805 executable is added in this PR because it is the only version that is statically linked and can be used in the hostOS. It is provided in the raspberrypi forums: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=250990
The latest public firmware release is obtained from the raspbian package repository, which DOES NOT have the fix needed yet. This PR should not be merged until the firmware fix is released.
Question has been addressed to the rpi maintainers for when and where will the firmware with the overheating fix will be available.</strike>
All vl805 binaries are now obtained from rpi-eeprom repository.

[RPi4] Add support for vl805 firmware update (without BalenaOS 2.45.0 update)

---

raspberrypi4-64.coffee

We only support 64 bits OS for the pi4 so let's not
explicitly mention it.
Changelog-entry: Remove the 64 bits OS reference from the rpi4 device pretty name

raspberrypi4-64.coffee: Clean-up device pretty name

---

layers/meta-balena-raspberrypi/conf/layer.conf

Customer request to have spi 3 to 6 enabled
in balenaOS
Changelog-entry: Enable spi3 to spi6 device tree overlays
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>

conf/layer.conf: Add spi3 to spi6 overlays

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-rpi-Disable-image-flasher-check.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

By default flasher check comes enabled from
meta-balena, but none of the raspberrypi
machines generate a flasher image.
Disabling this allows for adding 'usb' to
resin_uboot_device_types without actually
starting usb, unless and until it is confirmed that
there's no balena image on the sd-card.
With this change:
- uboot first attempts to load the kernel from the sd-card, if it is present and contains a balenaOS image. it looks no further for the usb, nor does it call "usb start" in this case.
- if no image is detected on the sd-card, usb will be started and checked for a balenaOS image, from where kernel will be loaded
Note: Added for rpi3-64, but we could very well extend for other machines too.
Addresses: https://github.com/balena-os/balena-raspberrypi/issues/341

u-boot: Disable flasher check, add usb

---

layers/meta-balena-raspberrypi/conf/layer.conf

We have added at customer request the device tree overlays for the
spi buses 3 to 6. But revpi-core-3 is running an older kernel which
does not have these overlays.
Changelog-entry: Remove spi3 to spi6 overlays for revpi-core-3 because it runs an older kernel which does not have them

conf/layer.conf: Remove spi3 to spi6 overlays from revpi-core-3

---

fincm3.coffee

The instructions for installing software on the Fin are not consistent with the actual hardware (at least the hardware that I have). On the UI it calls it the "DBG port" and on the hardware it's the "PRG port".  This PR includes the tiny change to make it so.

Update the Fin instructions to match the hardware.

---

layers/meta-balena-raspberrypi/conf/layer.conf

We add the uart2 to uart5 overlays to the rootfs alongside the
existing uart0 and uart1 overlays.
Changelog-entry: Add the uart2 to uart5 overlays to rootfs

layer.conf: Add uart2 to uart5 overlays

---

layers/meta-balena-raspberrypi/recipes-kernel/sd8887-mrvl/sd8887-mrvl-prebuilt.bb
layers/meta-balena-raspberrypi/recipes-kernel/sd8887-mrvl/sd8887-mrvl.bb

We have both bt8xxx and sd8xxx modules trying to use the same firmware
and do the same initilization for the Marvel bt / wifi chip. Since we
have bt8xxx loading first, let's add a 3 seconds delay until mlan loads
next in order to let the bt driver finish its init (and thus we avoid
wifi being unusable like in the following case:
[    6.618947] BT FW is active(6)
[    6.626161] mlan: module license 'Marvell Proprietary' taints kernel.
[    6.626175] Disabling lock debugging due to kernel taint
[    6.640429] BT: Driver loaded successfully
[    6.709945] wlan: Loading MWLAN driver
[   11.751740] Driver version = SD8887-0.0.0.p0-C4X15C651-GPL-(FP68)
[   11.751758] main_state = 0
[   11.751768] ioctl_pending = 0
[   11.751778] tx_pending = 0
[   11.751788] rx_pending = 0
[   11.751797] …

sd8887-mrvl: Delay mlan module loading

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-avoid-block-uart-write.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

It appears that when the console is incorrectly configured
in the dtb, booting will get stuck while trying to write
chars to the uart.
Let's avoid this by not blocking indefinitely.
Changelog-entry: u-boot: Prevent blocking when writing to serial console

u-boot: Prevent blocking when writing to serial console

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-fs-fat-allocate-a-new-cluster-for-root-directory-of-.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-fs-fat-flush-a-directory-cluster-properly.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-fs-fat-write-to-non-cluster-aligned-root-directory.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

We backport these 3 patches from upstream u-boot
2020.04 as they seem to fix a sporadic
HUP issue where boot count fails to be saved from
environment:
Error: allocating new dir entry
** Unable to write "bootcount.env" from mmc 0:1 **
FATWRITE FAILED
They seem to fix the issues with altboot here: https://github.com/balena-os/balena-raspberrypi/issues/470 and this one here: https://github.com/balena-os/balena-raspberrypi/issues/380
Issue seems to be reproducible after HUP-ing between releases, i.e. a 2.43 clean flash will not exhibit this, but a HUP to 2.43 will do. From that point on, consecutive HUPs to 2.48.0 will still exhibit the issue, both local and staging builds, both development and production. After HUP-ing to a build with these changes, the issue disappeared. 
Manged to …

u-boot: Fix FAT WRITE issue for bootcount

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

This PR enables Kvaser's CAN USB driver to support their USB interfaces.
The motivation is using a Balena Fin with a Kvaser Mini PCI Express HS interface or any other RPi based board with one of their USB interfaces (e.g, Leaf).

Enable Kvaser USB CAN driver

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend

At this moment we are using the default 2GB kernel / 2GB userspace
memory split which causes issues for the application that need to
map more than 2GB of memory (e.g. balena engine). The other 32-bit
boards default to 1GB kernel / 3GB userspace ratio which seems to
be more reasonable in general.
Changelog-entry: Use 1GB kernel / 3GB userspace memory split for 32-bit kernels
Signed-off-by: Michal Toman <michalt@balena.io>

linux-raspberrypi: Use 1GB kernel / 3GB userspace memory split for 32-bit kernels

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend

The PWRSEQ_SD8787 driver depends on either MWIFIEX or
BT_MRVL_SDIO and both are configured as modules.
Change the inclusion of PWRSEQ_SD8787 from built-in to
module to match the dependencies.

linux-raspberrypi: Remove kernel check config warning

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/rpi4-disable-pl01-serial-driver.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/rpi4-fix-usb-boot-8GB.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

In production images enable_uart is not set in config.txt
and we don't want to output anything to the console either.
Let's not load the pl11 serial driver for PI4 because it freezes boot when
enable_uart is not set.
Changelog-entry: Avoid freeze while booting production builds

u-boot: Avoid freeze while booting production builds

---

layers/meta-balena-raspberrypi/README.md

Changelog-entry: README: Rename resin to Balena in layer readme

README: Rename resin to Balena in layer readme

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-avoid-block-uart-write.patch

It was reported that in certain configurations
u-boot can possibly freeze with putc_retry located
in bss instead of data. This because the serial
driver is used before relocating.
Changelog-entry: u-boot: fix possible freeze in uart driver

u-boot: fix possible freeze in uart driver

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-overlays-Make-the-i2c-gpio-overlay-safe-again.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend

Pi3 does not boot if i2c-gpio overlay was loaded.
Backport fix from upstream so the Pi3 can boot again with this overlay enabled in config.txt.
Changelog-entry: linux-raspberrypi: Backport i2c-gpio fix for Pi3

linux-raspberrypi: Backport i2c-gpio overlay fix for Pi3

---

layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/bcm2835-bootfiles.bbappend

Changelog-entry: Use proper bootfiles for rt-rpi-300

bcm2835-bootfiles: Use proper bootfiles for rt-rpi-300

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend

While this makes it possible to run more containers on 32-bit RPi-s it makes the upper 256MB of memory unusable. We have tried to compensate with zram but that is not a suitable solution from a long-term perspective.

Revert "linux-raspberrypi: Use 1GB kernel / 3GB userspace memory split for 32-bit kernels"

---

layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bbappend

This gets added by u-boot in the form of root=UUID=
Changelog-entry: Remove explicit root cmdline parameter from the kernel recipe

linux-kunbus: Do not add explicit root cmdline parameter

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/pi4-fix-crash-when-issuing-usb-reset.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

With some specific USB keyboards or
arduinos, u-boot crashes on the pi4
when initializing usb. Avoid resetting
the board and continue to boot in these
cases.
Changelog-entry: u-boot: Don't crash with specific pi4 usb

u-boot: Don't crash with specific pi4 usb

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

The upstream kernel has disabled cgroups memory support by default and
made it a kernel argument in order to save memory;
https://github.com/raspberrypi/linux/commit/9b0efcc1ec497b2985c6aaa60cd97f0d2d96d203
BalenaOS requires this setting to be enabled.
Fixes https://github.com/balena-os/balena-raspberrypi/issues/574

linux-raspberry: Enable cgroups memory by default

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend
layers/meta-balena-raspberrypi/recipes-core/images/resin-image.bbappend

Updating of boot ROM on the Pi4 is not done
currently at hup, because it requires for
modules to be reloaded from container.
Let's drop these packages to make some space
for HUP.

resin-image: Drop bootrom update packages for pi4

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/serial_pl01x-Add-retry-limit-when-writing-to-uart-co.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

u-boot 2020.x switched to using the pl_01x driver which
locks up too if the uart is incorrecty configured
or is disabled from config.txt. We add a retry count
to avoid locking forever when serial isn't available.
Changelog-entry: u-boot: Avoid lockup on dev image with uart disabled
Addresses https://github.com/balena-os/balena-raspberrypi/issues/588

u-boot: Avoid lockup on dev images with uart disabled

---

layers/meta-balena-raspberrypi/recipes-core/images/resin-image.bbappend

Starting with kernel 5.4 a new device tree blob called overlay_map.dtb
was rolled out. This file needs to be placed in the overlays directory.
For details see
https://www.raspberrypi.org/documentation/configuration/device-tree.md
Changelog-entry: Fix overlay-map.dtb deploy location

resin-image: Fix overlay-map.dtb deploy location

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

This has been rolled back from 4.19 but has been copied to 5.4
inbetween and overlooked, we do not want to use it.
Changelog-entry: Use 2GB kernel / 2GB userspace memory split on 5.4 kernels
Change-type: minor
Signed-off-by: Michal Toman <michalt@balena.io>

linux-raspberrypi: Do not use VMSPLIT_3G on 5.4 kernel

---

layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-Add-tpm-slb9670-tis-spi-DT-overlay.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

We do ship a tpm-slb9670 DT overlay that loads the default slb9670
driver but there is HW that needs tis-spi driver instead.
This patch adds an overlay that will load the tis-spi driver
when applied.
Signed-off-by: Michal Toman <michalt@balena.io>

Add tpm-slb9670-tis-spi DT overlay

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0009-network-lan78xx-interrupt.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

Ethernet cable connect/disconnect events are not detected when a device is booted with the ethernet cable already connected.
This is a known issue: https://github.com/raspberrypi/linux/issues/2937
This commit applies an upstream patch that is already in the raspberrypi-linux rpi-5.4.y and rpi-5.10.y branches.
Tested on a Raspberry Pi 3 B+ with balenaOS v2.69.1+rev2.
Connects-to: #605
Changelog-entry: meta-balena-raspberrypi/linux: fix ethernet cable detection
Signed-off-by: Mark Corbin <mark@balena.io>

meta-balena-raspberrypi/linux: fix ethernet cable detection

---

layers/meta-balena-raspberrypi/conf/samples/local.conf.sample

We do so because all new added devices
should use overlay2 by default.
Changelog-entry: conf/samples: Switch HNT device to overlay2

conf/samples: Switch HNT device to overlay2

---

layers/meta-balena-raspberrypi/conf/machine/nebra-hnt.conf
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/rpi4-disable-pl01-serial-driver.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/0001-Allow-using-obexd-without-systemd-in-the-user-sessio.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/0001-test-gatt-Fix-hung-issue.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/0001-tests-add-a-target-for-building-tests-without-runnin.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/fix-registerin-dis-without-valid-source.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/init
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/main-conf-enable-passing-false-deviceid.patch
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5/nebra-hnt/run-ptest
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5_5.56.bb

The 000x patches, init and run-ptest come from poky
bluez 5.55, the other two are backported from github
bluez issue 101. We update to Bluez 5.56 to apply these
two pending patches and check if they solve an issue
that affects this board's use-case.

bluez5: Add pending upstream patches for Nebra HNT

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

We include this change for all the rpi boards, Pi4
uses an updated u-boot for pi400 and cm4 support
so it needs a slightly rebased version of the patch.
Change-type: Patch

u-boot: include previous version for pl01 patch

---

fincm3.coffee
layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-Integrate-machine-independent-resin-environment-conf.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend
layers/meta-balena-raspberrypi/recipes-core/images/balena-image.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend
layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
nebra-hnt.coffee
npe-x500-m3.coffee
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3-64.coffee
raspberrypi3.coffee
raspberrypi4-64.coffee
raspberrypi400-64.coffee
raspberrypicm4-ioboard.coffee
revpi-connect.coffee
revpi-core-3.coffee
rt-rpi-300.coffee

Rename resin image types to balena and replace RESIN_ env vars
Changelog-entry: Rename resin image types to balena
Signed-off-by: Kyle Harding <kyle@balena.io>

balena-raspberrypi: Rename resin image types to balena

---

layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner

Replace all references to the 'resin-vars' script with 'balena-config-vars' as it has been renamed.
This PR needs to be merged when https://github.com/balena-os/meta-balena/pull/2142 has been merged.
Changelog-entry: balena-raspberrypi: replace references to resin-vars
Signed-off-by: Mark Corbin <mark@balena.io>

balena-raspberrypi: replace references to resin-vars

---

layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_%.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-seeed-studio-can-bus-v2-Add-dtbo-for-this-can-bus.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend

It is reported that the latest version of the
BCM4345C0 fw file fixes various bluetooth issues
and sporadic disconnections.
Changelog-entry: bluez-firmware-rpidistro: Update to latest revision
Siged-off-by: Alexandru Costache <alexandru@balena.io>
Addresses: https://github.com/balena-os/balena-raspberrypi/issues/635

bluez-firmware-rpidistro: Update to latest revision

---

raspberrypi3-unipi-neuron.coffee

Changelog-entry: Fix typo in raspberrypi3-unipi-neuron.coffee file

raspberrypi3-unipi-neuron.coffee: Fix typo

---

layers/meta-balena-raspberrypi/recipes-extended/unipi-tools/unipi-tools.bb

The binaries were missing execution bit set and also we were missing the
libmodbus dependency in the rootfs.
Changelog-entry: Fix unipi-tools binaries installation

unipi-tools: Fix binaries install

---

layers/meta-balena-raspberrypi/conf/layer.conf

Include the mcp251xfd overlay to rootfs as per popular demand
Changelog-entry: Add mcp251xfd overlay to rootfs

meta-balena-raspberrypi:layer.conf: Add mcp251xfd overlay to rootfs

---

revpi-connect.coffee

Update meta-balena from 2.75.0 to 2.77.0
Changelog-entry: Update meta-balena from v2.75.0 to v2.77.0

layers/meta-balena: Update to v2.77.0

---

layers/meta-balena-raspberrypi/conf/layer.conf

Because the BSP in the dunfell branch does not currently ship these dtbs
in the raspberrypi4-64 machine let's just add it from here instead.
Changelog-entry: Add bcm2711-rpi-400.dtb and bcm2711-rpi-cm4.dtb for the raspberrypi4-64 machine

meta-balena-raspberrypi:layer.conf: Add rpi-400,rpi-cm4 dtbs for rpi4-64

---

layers/meta-balena-raspberrypi/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend

Hello! I had requested a previous change to enable support for a specific USB Wifi adapter for the Raspberry PI CM4. See https://github.com/balena-os/balena-raspberrypi/pull/705)
[However, the adapter I had requested does not support Access point mode (contrary to documentation)](https://github.com/balena-os/wifi-connect/issues/413), meaning that the Wifi-Connect service cannot be used with it.
I am submitting this change to allow use of the [Panda Wireless Adapters](https://www.amazon.com/dp/B00762YNMG?psc=1&ref=ppx_yo2_dt_b_product_details) which are well supported by Network Manager and will allow use of Wifi Connect. 
These adapters use the rt2870.bin file provided by linux-firmware-ralink.
I believe this change is the only one that is required. Let me know what else needs to happen!

Restore linux-firmware-ralink firmware for cm4-ioboard and pi400

---

layers/meta-balena-raspberrypi/conf/layer.conf

Include the PoE+ overlay to rootfs for supporting this newer hat
Changelog-entry: Add Raspberry Pi PoE+ overlay to rootfs

meta-balena-raspberrypi:layer.conf: Add PoE+ overlay to rootfs

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0011-USB-serial-Add-support-for-more-Quectel-modules.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.10.bbappend

We added kernel changes as instructed by Quectel:
https://github.com/balena-os/balena-raspberrypi/issues/736
Changelog-entry: Add support for additional Quectel modems

linux-raspberrypi: Add support for additional Quectel modems

---

layers/meta-balena-raspberrypi/conf/layer.conf

Add fbtft for SPI-connected displays
https://github.com/notro/fbtft/wiki/FBTFT-RPI-overlays
Change-type: minor
Changelog-entry: conf/layer: Add fbtft overlay for SPI-connected displays
Signed-off-by: Rahul Thakoor <rahul@balena.io>

Add fbtft dtoverlay for SPI-connected displays

---

layers/meta-balena-raspberrypi/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_%.bbappend

Some device types like the RaspberryPi place non-firmware files under
`/lib/firmware`. This commit skips compression for them.

balena-linux-firmware: Do not compress non-binary txt files

---

raspberrypi0-2w-64.coffee

Contracts PR [284](https://github.com/balena-io/contracts/pull/284) changed the name of the
device from Raspberry Pi Zero 2 Wifi to Raspberry Pi 0
2 W, let's update this in the coffee file too.
Changelog-entry: raspberrypi0-2w-64: Rename Wifi to W in coffee file
Fixes https://github.com/balena-os/balena-raspberrypi/issues/790

raspberrypi0-2w-64: Rename Wifi to W in coffee file

---

layers/meta-balena-raspberrypi/conf/layer.conf

Until the patch from Michal gets merged in
upstream meta-raspberrypi honister branch we
can include the overlay on our side to solve fkms not
loading properly. When this overlay is not included,
vcdbg displays the following error:
007119.598: Failed to load overlay 'vc4-fkms-v3d'
Changelog-entry: conf/layer: Include vc4-fkms-v3d-pi4 overlay
Connects-to: https://github.com/balena-os/balena-raspberrypi/issues/785

conf/layer: Include vc4-fkms-v3d-pi4 overlay

---

layers/meta-balena-raspberrypi/conf/layer.conf

Add required dtoverlays for camera modules as per [documentation](https://www.raspberrypi.com/documentation/accessories/camera.html#getting-started)
Changelog-entry: conf/layer: Include camera module dtoverlays
Signed-off-by: Rahul Thakoor <rahul@balena.io>

conf/layer: Include camera module dtoverlays

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-avoid-block-uart-write.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/serial_pl01x-Add-retry-limit-when-writing-to-uart-co.patch

The Pi3 32bit currently refuses to boot if
gpu_mem is set to 396MB. This seems to be caused
by a variable we use in u-boot to avoid locking
while writing to the uart, if enable_uart is
disabled in config.txt.
Having the putc_retry variable uninitialized
meant that it was part of the data section,
however this no longer seems to be the case and
we need to allocate it in .data explicitly.
Changelog-entry: u-boot: fix Pi3 booting with large gpu_mem

u-boot: Ensure uart retry count is stored in data section

---

layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/unipi-kernel-modules.bb

The vendor now redirects
https://git.unipi.technology/UniPi
to https://github.com/UniPiTechnology/
so let's follow suite.
Changelog-entry: Use updated SRC_URI for unipi kernel modules

unipi-kernel-modules.bb: Switch SRC_URI

---

layers/meta-balena-raspberrypi/recipes-kernel/sd8887-nxp/sd8887-nxp.bb

This avoids the following build warning:
WARNING: /build/balena-raspberrypi/build/../layers/meta-balena-raspberrypi/recipes-kernel/sd8887-nxp/sd8887-nxp.bb: Recipe sd8887-nxp sets B variable with trailing slash '/build/balena-raspberrypi/build/tmp/work/raspberrypi4_64-poky-linux/sd8887-nxp/1.0-r0/git/software/drivers/sd8887/', remove it

sd8887-nsp: Avoid build warning removing trailing slash from source var

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.10.bbappend

Changelog-entry: linux-raspberrypi: Enable NFSv4 config
Signed-off-by: Kyle Harding <kyle@balena.io>
See: https://github.com/balena-os/balena-raspberrypi/issues/892

linux-raspberrypi: Enable NFSv4 config

---

.github/workflows/build_and_deploy.yml

The final argument is now filled up dynamically.
Changelog-entry: Remove final argument from build and deploy workflow

workflows: build and deploy: Remove final argument

---

layers/meta-balena-raspberrypi/conf/samples/bblayers.conf.sample

Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering

bblayers: Modify layer ordering

---

layers/meta-balena-raspberrypi/recipes-core/images/balena-image.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

This issue has not been reproduced locally in 3 build attempts, so we need to see if this happens in Jenkins and at what build step.

Fix missing file gpio-poweroff.dtbo

---

layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

Requires https://github.com/balena-os/meta-balena/pull/2982
Changelog-entry: Modify bluez patches for v5.66 update

bluez5: modify patches for v5.66 update

---

layers/meta-balena-raspberrypi/conf/samples/bblayers.conf.sample

Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf

bblayers.conf.sample: add meta-perl

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bbappend

These have been requested by customers to use with their applications.
Fixes #821
Changelog-entry: Add IIO pressure kernel drivers

linux-raspberrypi: Add IIO pressure kernel drivers

---

.gitmodules

Autohat is no longer used as a testing framework for balenaOS.
Changelog-entry: remove autohat from gitmodules

.gitmodules: remove autohat as it's deprecated

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-bootfiles.bbappend

We do this so we don't need to always increase this list we check each time we add new raspberrypi4-64 based machines. Instead, we rely on the fact that all new RPI4 based machines will inherit the raspberrypi4-64 machine.
Changelog-entry: Make the boot firmware filtering for rpi4 based hw generic

rpi-bootfiles.bbappend: Make the firmware filtering generic

---

layers/meta-balena-raspberrypi/recipes-extended/phoenix-peripheral/phoenix-peripheral.bb

Since we are using Poky Kirkstone we need to use the proper syntax
Changelog-entry: Fix phoenix-peripheral RDEPENDS syntax in order to have watchdog in rootfs for raspberrypi4-superhub

phoenix-peripheral.bb: Fix faulty RDEPENDS

---

layers/meta-balena-raspberrypi/recipes-extended/watchdog/watchdog/0001-Move-watchdog-service-before-networking.patch
layers/meta-balena-raspberrypi/recipes-extended/watchdog/watchdog_5.16.bbappend

This update brings in changes needed to speedup watchdog startup
Changelog-entry: Update watchdog config for superhub device type

watchdog: Modify watchdog systemd startup for superhub device

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-bootfiles.bbappend

This update is needed for newer revisions of the hw (Pi 3 A+ PCB R2 for example)
Changelog-entry: Update rpi firmware to version 20230509 for newer hw revisions

rpi-bootfiles.bbappend: Update rpi firmware to version 20230509

---

layers/meta-balena-raspberrypi/recipes-core/images/balena-image-initramfs.bbappend
layers/meta-balena-raspberrypi/recipes-core/initrdscripts/initramfs-framework_%.bbappend

The Revolution Pi are particular devices as they define an internal storage in the contract, but they dos not use a flasher image and instead rely on the bootloader's exposing the internal storage.
However, resin-init-flasher has a built time check for all devices that define internal storage to define INTERNAL_DEVICE_KERNEL, so the build fails when initramfs-framework builds the resin-init-flasher dependency.
The lack of a `jq` dependency on earlier versions of meta-balena meant that the check was non-operative, but it started failing when the dependency was added.
This commit removes the migrator module from being built and included in the initramfs.
Relates-to: https://github.com/balena-os/meta-balena/pull/3317
Changelog-entry: remove migrator module for revpi family

initramfs-framework: revpi:remove migrator module

---

layers/meta-balena-raspberrypi/recipes-core/systemd/systemd/rpi/balena-os-sysctl.conf
layers/meta-balena-raspberrypi/recipes-core/systemd/systemd_%.bbappend

On long run reboot tests we have seen devices get stuck on reboot when systemd-shutdown hangs and systemd is still refreshing the hardware watchdog. Those devices are unreachable until power cycled.
To avoid this, we configure the devices to panic on hung task detection which will reboot the device. However, as we know the engine might hang itself when pulling big images, we also extend the timeout from 2m to 4m to try and avoid this.
Changelog-entry: configure panic on hung tasks and extend timeout

systemd: configure panic on hung tasks and extend timeout

---

layers/meta-balena-raspberrypi/conf/machine/include/revpi4.inc

Move the SOC_MACHINE setting before the MACHINEOVERRIDES immediate assignment so it gets taken into account when setting MACHINEOVERRIDES.
Otherwise the `revpi` machine override gets lost.
Changelog-entry: apply revpi machine override for revpi4 family

conf: machine: revpi4: move SOC_MACHINE so it sets correctly

---

layers/meta-balena-raspberrypi/classes/image-sign-rpi.bbclass

At this moment `do_balena_signed_bootgen_and_deploy` and `do_image_balenaos_img` tasks run in parallel, which is causing problems as `do_image_balenaos_img` needs to use the output of `do_balena_signed_bootgen_and_deploy` to generate the contents of the boot partition. Since the call to the signing server takes several seconds, sometimes `boot.sig` or `boot.img` or both are not included in the final image, depending on when `do_image_balenaos_img` is actually executed.
This patch reorders the tasks so that `do_image_balenaos_img` is only started after `do_balena_signed_bootgen_and_deploy`.

image-sign-rpi.bbclass: reorder tasks to avoid missing boot files

---

layers/meta-balena-raspberrypi/recipes-core/images/balena-image-bootloader-initramfs.bbappend
layers/meta-balena-raspberrypi/recipes-core/images/balena-image-initramfs.bbappend
layers/meta-balena-raspberrypi/recipes-core/initrdscripts/files/kexec_pi4_fwgpio
layers/meta-balena-raspberrypi/recipes-core/initrdscripts/initramfs-framework_%.bbappend

The Pi4 devices (Pi4, CM4, Pi400) use an internal 8-pin GPIO header to control some firmware features including wifi and bluetooth. Initially these are set up by the broadcom bootloader, but after kexec (which the balena bootloader uses), they are all reset to zeroes. This means wifi and bluetooth "disappear" after kexec.
This patch adds an initrd scripts that reads the GPIO pin values before kexec and appends them as an extra kernel argument. After kexec, it reads the kernel argument and restores the pin values to what they originally were.
This depends on https://github.com/balena-os/meta-balena/pull/3445, it won't break anything without it, but won't work either.

initrdscripts: Restore the state of Pi4/CM4 firmware GPIOs after kexec

---

layers/meta-balena-raspberrypi/recipes-bsp/rpi-eeprom/rpi-eeprom_git.bb
layers/meta-balena-raspberrypi/recipes-devtools/usbboot/usbboot-native_git.bb

The rpi-eeprom recipe is using 3b393d31ac0f1864420d47028b5703a70ad8da8f.
This commit updates the usbboot recipe to build a version that includes the above EEPROM firmware.
Changelog-entry: update usbboot to match EEPROM firmware version

usbboot: update to match the EEPROM firware version

---

layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus_6.1.46.bb

Builds recently started failing with the following error:
fatal: unable to access 'https://gitlab.com/revolutionpi/linux/': Failed to connect to gitlab.com port 443: No route to host
Changelog-entry: Fix SRC_URI format for linux-kunbus_6.1.46

linux-kunbus_6.1.46.bb: Fix SRC_URI

---

layers/meta-balena-raspberrypi/recipes-core/systemd/systemd/rpi/watchdog.conf

By default, the second stage watchdog time that is used to set the watchdog once systemd-shutdown has stopped all services and replaced PID1 with itself is set to 10m.
However, the RPI watchdog has a maximum timeout of 15s, so we adjust this value accordingly.
This helps ensure that when a shutdown or reboot is triggered, the device can fallback to a watchdog reboot if it gets stuck.
Changelog-entry: adjust reboot watchdog timeout

systemd-shutdown: adjust watchdog expiration time

---

layers/meta-balena-raspberrypi/recipes-core/extra-udev-rules/extra-udev-rules.bbappend
layers/meta-balena-raspberrypi/recipes-core/extra-udev-rules/files/50-revpi.rules
layers/meta-balena-raspberrypi/recipes-core/extra-udev-rules/files/revpi_mac

Add RevPi specific udev rules and helper script for mac address configuration from HAT eeprom. The ruleset will ensure that the following things behave similar to a stock RevPi OS:
- Alias for RS485 interfaces (eg. /dev/ttyRS485)
- Set mac address from HAT EEPROM for interfaces without own eeprom
- Set interfaces names according to device markings
- Use correct interface names for PiBridge ethernet interfaces (without this gateways can't work with piControl)
Changelog-entry: Add RevPi udev rules

Add RevPi specific udev rules

---

layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-avoid-block-uart-write.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-rpi-Disable-image-flasher-check.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/Revert-remove-include-config_defaults.h.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/pi4-fix-crash-when-issuing-usb-reset.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/rpi4-include-configs-Use-config-defaults.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/serial_pl01x-Add-retry-limit-when-writing-to-uart-co.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/u-boot-Remove-usb-start-from-CONFIG_PREBOOT.patch

As indicated at https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status
Changelog-entry: Correct the Upstream-Status of u-boot patches

u-boot: Correct patches' Upstream-Status

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend

Changelog-entry:  revpi-connect-4: configure to use external antenna by default
PCB antenna on the CM4 has signal issues through the revpi connect 4 enclosure - configuring to use the external antenna provides improvement even without an antenna attached.

revpi-connect-4: configure to use external antenna by default

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-overlays-Add-overlay-for-RPI-PLC-SC16IS752.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bbappend

This overlay is a modified version from https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/overlays/sc16is752-spi1-overlay.dts

Add custom overlay for SC16IS752 used in Industrial Shields RPI PLC

---

.github/workflows/npe-x500-m3.yml
.github/workflows/raspberrypi.yml
.github/workflows/raspberrypi0-2w-64.yml
.github/workflows/raspberrypi2.yml
.github/workflows/raspberrypi3-64.yml
.github/workflows/raspberrypi3-unipi-neuron.yml
.github/workflows/raspberrypi3.yml
.github/workflows/raspberrypi4-64.yml
.github/workflows/raspberrypi4-superhub.yml
.github/workflows/raspberrypi4-unipi-neuron.yml
.github/workflows/raspberrypi400-64.yml
.github/workflows/raspberrypi5.yml
.github/workflows/raspberrypicm4-ioboard.yml
.github/workflows/revpi-connect-4.yml
.github/workflows/revpi-connect-s.yml
.github/workflows/revpi-connect.yml
.github/workflows/revpi-core-3.yml
.github/workflows/rt-rpi-300.yml

This enables manual testing of meta-balena PRs directly on device repos.
Changelog-entry: Allow custom meta-balena ref on workflow dispatch

Allow overriding the meta-balena ref for workflow dispatch

---

layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-support/hostapp-update-hooks/files/9999-bootfiles

The default CMA size has been 320M until the 6.1.y kernel increased it to 512M in 9b523e1fc8a786da6fb6e0a8301d2fb4a2332dbb.
This breaks applications that were setting high `gpu_mem` values as the combination of CMA + GPU memory cannot exceed 32bit DMA accessible memory.
This commit explicitely sets 320M as default to keep backwards compatibility.

Explicitely set the default CMA size

---

layers/meta-balena-raspberrypi/recipes-connectivity/pi-bluetooth/pi-bluetooth_%.bbappend

Using the nonarch_base_libdir variable instead of hardcoding directly the path will help us when we enable the usrmerge feature.
Changelog-entry: Use nonarch_base_libdir variable when packaging files for pi-bluetooth recipe

pi-bluetooth_%.bbappend: Use nonarch_base_libdir variable

---

layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend

See https://www.raspberrypi.com/documentation/computers/config_txt.html#otg_mode-raspberry-pi-4-only for details on this option
Changelog-entry: Enable the XHCI USB 2 controller to be used as a host controller on the USB-C connector for CM4 devices

rpi-config: Enable otg_mode setting for cm4 based devices

---

layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro/0001-Default-43455-firmware-to-standard-variant.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb

This update brings in additional WiFi firmware for various RPi models.
This is taken from meta-raspberrypi master branch at revision cd558f77b6b1a6d0fa15cd9558df0c0262d42c91
Also, this also needs a local.conf change to accept the synaptics-killswitch license but as per https://github.com/RPi-Distro/firmware-nonfree/issues/29#issuecomment-1795717241 it should be fine.
Changelog-entry: Update linux-firmware-rpidistro to version 20230625-2+rpt3 for newer wifi firmware

linux-firmware-rpidistro_git: Update to version 20230625-2+rpt3

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-balena-bootloader_6.12.bb
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.12.bb

This also unifies kernel and balena-bootloader versions.

linux-raspberrypi: Update to 6.12.25

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-balena-bootloader_6.12.bb
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.12.bb

The previous update to 6.12.25 has introduced issues with video decoding at least on Pi4 and Pi5, this should address them.

linux-raspberrypi: Update to 6.12.30

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-balena-bootloader_6.12.bb
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.12.bb
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.12.inc

Include better lock handling when calling find_vdma() https://github.com/raspberrypi/linux/pull/6868

linux-raspberrypi: Update to 6.12.32

---

layers/meta-balena-raspberrypi/conf/layer.conf

At this moment we're defaulting to the minimal variant of the cyfmac43455-sdio firmware on all devices except Pi5. We inherit this from upstream, who switched to minimal in Jan 2025.
This patch makes all the devices ship default to the full variant, which makes it possible to connect to WPA3 networks.

layer.conf: Use full version of cyfmac43455-sdio firmware
