balena-os/balena-raspberrypi

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/bblayers.conf.sample
raspberrypi.coffee
raspberrypi2.coffee

@agherzan @floion
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-raspberrypi/2)

Transition to jethro

---

CHANGELOG.md

Signed-off-by: Theodor Gherzan <theodor@resin.io>
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-raspberrypi/4)

.gitmodule: Hotfix jethro revision

---

layers/meta-resin-raspberrypi/recipes-core/images/resin-image.bbappend

@agherzan @floion
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-raspberrypi/6)

RPI 1/2 fix 

---

.gitmodules
layers/meta-resin-raspberrypi/conf/samples/bblayers.conf.sample

Switch to docker

---

raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3.coffee

Relies on https://github.com/resin-os/resin-yocto-scripts/pull/11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-raspberrypi/12)

Compressed artifacts

---

CHANGELOG.md

Bluetooth support on raspberypi3

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/local.conf.sample

Improve build disk usage

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend

Mask brcm43438.service#22

---

layers/meta-resin-raspberrypi/recipes-core/images/resin-image.bbappend

Fix overlays deploy dir

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/local.conf.sample

Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg

Replace SUPERVISOR_TAG by TARGET_TAG on resin-raspberrypi

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

@floion @telphan @petrosagg
Connects to resin-os/resin-beaglebone#18

Compress kmodules

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/local.conf.sample

Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg

Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-raspberrypi

---

layers/meta-resin-raspberrypi/recipes-bcm/bootfiles/rpi-config_git.bbappend
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

@floion @telphan 
Connects to #34

Fix debug image

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

Signed-off-by: Theodor Gherzan <theodor@resin.io>

Fix console output in production

---

layers/meta-resin-raspberrypi/README.md

Signed-off-by: Andrei Gherzan <andrei@resin.io>
@telphan @floion @petrosagg @lorenzo-stoakes

README.md: Add info about getty on serial port

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

Fix kernel console output on production

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-bcm/bootfiles/rpi-config_git.bbappend

Connects to https://github.com/resin-os/resin-raspberrypi/issues/39

Disable firmware related output

---

.gitmodules
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3.coffee

This implements resin-os/resin-yocto-scripts#31
Signed-off-by: Eugene Mirotin eugene@resin.io
@agherzan @floion

Update to use the simplified JSON building process on resin-raspberrypi

---

CHANGELOG.md
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3.coffee

@agherzan @michal-mazurek @telphan

Switch partition with conf in coffee

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/samples/local.conf.sample

Connects to resin-os/meta-resin#315

Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

---

layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

Signed-off-by: Andrei Gherzan <andrei@resin.io>

linux-raspberrypi: debug-image was replaced

---

README.md

Connects to contributing
@telphan @floion @michal-mazurek

Add Contributing section on resin-raspberrypi

---

CHANGELOG.md

* Update resin-yocto-scripts to fix logging in container builds on resin-raspberrypi

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

@petrosagg @michal-mazurek @telphan

Autoload watchdog module

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

@petrosagg @michal-mazurek @telphan

Autoload watchdog module 1.x

---

CHANGELOG.md
layers/meta-resin-raspberrypi/conf/layer.conf

Connected to https://github.com/resin-os/resinos/issues/188

dt overlays morty

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend

Fixes https://github.com/resin-os/resinos/issues/252

Default with audio on

---

CHANGELOG.md

This makes the build scripts match the master branch so the two Jenkins configs can be in sync.

Update build scripts on the 1.X branch

---

CHANGELOG.md

This includes changes to fix the Pyro build but also includes a change to the arguments of the build script so will require changing the Jenkins config or the build will fail.

Update build scripts to latest master

---

CHANGELOG.md
layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

linux-raspberrypi: Bump kernel to 4.9.59

---

CHANGELOG.md

Signed-off-by: Andrei Gherzan <andrei@resin.io>

Release v2.11.1+rev1

---

CHANGELOG.md
raspberrypi3.coffee

Signed-off-by: Gergely Imreh <imrehg@gmail.com>

Update warning in the dashboard regarding the RPi3 wifi connectivity.

---

.gitmodules

- Updated meta-resin to 2.28
- Switched resin-yocto-scripts to balena-yocto-scripts

Update meta-resin to 2.28

---

layers/meta-resin-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bbappend

Add revpi rt kernel configs

---

README.md

Changelog-entry: Add info for PR contributions to README.md

README.md: Add info for PR contributions

---

raspberrypi3-64.coffee

Changelog-entry: Change the pretty name for Raspberry Pi 3 on 64 bits

raspberrypi3-64.coffee: Change the pretty name

---

fincm3.coffee
layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/conf/samples/bblayers.conf.sample
layers/meta-balena-raspberrypi/recipes-connectivity/bluez5/bluez5_%.bbappend
layers/meta-balena-raspberrypi/recipes-connectivity/pi-bluetooth/pi-bluetooth_%.bbappend
layers/meta-balena-raspberrypi/recipes-core/images/resin-image.bbappend
layers/meta-balena-raspberrypi/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3-64.coffee
raspberrypi3.coffee
revpi-core-3.coffee

This is a draft PR because it needs merged and released support in meta-balena: https://github.com/balena-os/meta-balena/pull/1351
Tested on:
* RaspberryPi3
* fin3
* Generic X86

Yocto Thud support in balena-raspberrypi

---

layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus/0002-NFLX-2019-001-SACK-Panic.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus/0003-NFLX-2019-001-SACK-Panic-for-lteq-4.14.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus/0004-NFLX-2019-001-SACK-Slowness.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus/0005-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux-kunbus/linux-kunbus/0006-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0002-NFLX-2019-001-SACK-Panic.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0003-NFLX-2019-001-SACK-Panic-for-lteq-4.14.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0004-NFLX-2019-001-SACK-Slowness.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0005-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0006-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

ID: NFLX-2019-001
Title: Linux and FreeBSD Kernel: Multiple TCP-based remote denial of service vulnerabilities
Release Date: 2019-06-17
Severity: Critical

Netflix patches

---

raspberrypi2.coffee

Signed-off-by: Chris Crocker-White <chriscw@balena.io>

Add warning advising of no WiFi on Pi 2

---

raspberrypi3-64.coffee
raspberrypi4-64.coffee

Change the state field to 'released'
instead of 'experimental'
Changelog-entry: Change the state to 'released' in the coffee files
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>

coffee: Set state to 'released'

---

npe-x500-m3.coffee
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3-64.coffee
raspberrypi3.coffee
raspberrypi4-64.coffee

Updating getting started links from resin.io to balena.io.
One commit per file changed and a single changelog entry.

Updating getting started links

---

fincm3.coffee

Let me know if you want me to squash these as changing the same file. I realized I missed updating getting started links on this file.

Updating steps to power device for each Fin version

---

fincm3.coffee
npe-x500-m3.coffee
raspberrypi.coffee
raspberrypi2.coffee
raspberrypi3-64.coffee
raspberrypi3.coffee
raspberrypi4-64.coffee
revpi-core-3.coffee

Changelog-entry: Set private to false in .coffee files for the public device types

.coffee: Set private to false for the public device types

---

README.md

Changelog-entry: Dummy commit for triggering vb

README.md: Slight change to trigger vb

---

layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr/raspberrypi3-64/boot.cmd.in

Update meta-balena from 2.56.0 to v2.58.0
Changelog-entry: Update meta-balena from v2.56.0 to v2.58.0

layers/meta-balena: Update to v2.58.0

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend

Update meta-balena from 2.58.0 to v2.58.3
Changelog-entry: Update meta-balena from v2.58.0 to v2.58.3

layers/meta-balena: Update to v2.58.3

---

layers/meta-balena-raspberrypi/conf/machine/rt-rpi-300.conf
layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
rt-rpi-300.coffee
rt-rpi-300.svg

Changelog-entry: Add rt-rpi-300 machine based on Raspberry Pi4

rt-rpi-300: Add new machine

---

layers/meta-balena-raspberrypi/recipes-connectivity/pi-bluetooth/files/0003-bthelper-Set-BDADDR-if-not-initialized.patch
layers/meta-balena-raspberrypi/recipes-connectivity/pi-bluetooth/pi-bluetooth_%.bbappend

Addresses https://github.com/balena-os/balena-raspberrypi/issues/731

cm4: Fix bdaddr not set at boot

---

layers/meta-balena-raspberrypi/conf/layer.conf

Changelog-entry: conf/layer: Add vc4-kms-dsi-7inch overlay

conf/layer: Add vc4-kms-dsi-7inch overlay

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-Revert-overlays-i2c-gpio-Avoid-open-drain-warnings.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.10.bbappend

This fixes https://github.com/balena-os/balena-raspberrypi/issues/640
Signed-off-by: Joseph Kogut <joseph@balena.io>

linux: fincm3: revert 129d946 to work around open drain issue

---

.gitmodules
layers/meta-balena-raspberrypi/conf/layer.conf
layers/meta-balena-raspberrypi/conf/samples/bblayers.conf.sample
layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-bootfiles.bbappend
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-Integrate-machine-independent-resin-environment-conf.patch
layers/meta-balena-raspberrypi/recipes-bsp/u-boot/u-boot/0001-rpi-Disable-image-flasher-check.patch
layers/meta-balena-raspberrypi/recipes-core/images/balena-image.bbappend
layers/meta-balena-raspberrypi/recipes-extended/unipi-tools/unipi-tools.bb
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0001-waveshare-sim7600-Add-dtbo-for-this-modem.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0004-mmc-pwrseq-Repurpose-for-Marvell-SD8777.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/rt-rpi-300-Add-changes-for-this-dt.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bbappend
layers/meta-balena-raspberrypi/recipes-kernel/picontrol/picontrol.bb
layers/meta-balena-raspberrypi/recipes-kernel/sd8887-nxp/sd8887-nxp.bb
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0001-unipi_tty-Fix-compile-on-kernel-5.10.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0002-unipi_spi-use-new-structure-for-SPI-transfer-delays.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0003-unipi_tty-remove-TTY_LDISC_MAGIC.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0004-unipi_tty-remove-ldisc-number-in-tty_register_ldisc-.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0005-unipi_tty-adapt-to-fp-of-tty_ldisc_ops-made-const.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0006-unipi_spi-adapt-to-removal-of-spi_set_cs_timing.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0007-rtc-unipi-Adapt-to-removal-of-nvram-ABI.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0008-rtc-unipi-Add-devm-to-rtc_nvmem_register.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/files/0009-rtc-unipi-Adapt-to-rename-of-rtc_register_device.patch
layers/meta-balena-raspberrypi/recipes-kernel/unipi-kernel-modules/unipi-kernel-modules.bb

Requires https://github.com/balena-os/meta-balena/pull/2803
Requires https://github.com/balena-io-hardware/balena-fin/pull/98

Update to kirkstone

---

.github/workflows/flowzone.yml

Update meta-balena from 2.112.15 to 2.112.16
Changelog-entry: Update meta-balena from v2.112.15 to v2.112.16

layers/meta-balena: Update to v2.112.16

---

fincm3.coffee

Changelog-entry: Flag the fincm3 as discontinued

fincm3: flag as discontinued

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bbappend

linux-raspberrypi: update to latest stable head 5.15.92

---

layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bbappend

Depends-on: https://github.com/balena-os/meta-balena/pull/3376

Fix kernel configuration checks warnings

---

layers/meta-balena-raspberrypi/conf/machine/nebra-hnt.conf
layers/meta-balena-raspberrypi/conf/machine/raspberrypi4-superhub.conf
layers/meta-balena-raspberrypi/conf/machine/raspberrypi4-unipi-neuron.conf
layers/meta-balena-raspberrypi/conf/machine/raspberrypi400-64.conf
layers/meta-balena-raspberrypi/conf/machine/raspberrypicm4-ioboard-sb.conf
layers/meta-balena-raspberrypi/conf/machine/raspberrypicm4-ioboard.conf

Changelog-entry: Use append style for MACHINEOVERRIDES

Use append style for MACHINEOVERRIDES

---

.github/workflows/raspberrypicm4-ioboard.yml

This is a public dt so let's do as for the other public device types.
Changelog-entry: Set raspberrypicm4-ioboard to run the tests against the bm instance

raspberrypicm4-ioboard.yml: Run the tests on the bm instance

---

layers/meta-balena-raspberrypi/conf/machine/raspberrypi4-edatec-sensing.conf
layers/meta-balena-raspberrypi/conf/samples/local.conf.sample
layers/meta-balena-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend
layers/meta-balena-raspberrypi/recipes-core/extra-udev-rules/extra-udev-rules.bbappend
layers/meta-balena-raspberrypi/recipes-core/extra-udev-rules/files/98-com-sensing.rules
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi/raspberrypi4-edatec-sensing/0001-Add-ed-mcp2515-overlay-and-ed-sdhost-overlay.patch
layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.12.bbappend
raspberrypi4-edatec-sensing.coffee

Changelog-entry: Add support for EDATEC CM4 Sensing

Add support for EDATEC CM4 Sensing

---

docs/rpi-secure-boot.md

For the time being the final locking needs to be a manual process - make sure it's detailed in the documentation.

docs: rpi-secure-boot: add detailed manual provisioning instructions
